/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.etsmtl.log720.lab1.view;

import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Scanner;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

import ca.etsmtl.log720.lab1.ClientVoitureSingleton;
import ca.etsmtl.log720.lab1.CollectionInfraction;

/**
 *
 * @author Steven
 */
public class Infractions extends javax.swing.JFrame {

    /**
     * Creates new form Infractions
     */
    private Infractions() {
        initComponents(new ActionListener(){
			public void actionPerformed(ActionEvent arg0) {
				// TODO Auto-generated method stub
				
			}
        });
    }
    
    public Infractions(ActionListener _listener) {
        initComponents(_listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents(ActionListener _listener) {
        jScrollPane2 = new javax.swing.JScrollPane();
        jL_list_infractions = new java.awt.List();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        selectedInfraction = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jL_niveauGravite = new javax.swing.JLabel();
        jB_add_infToDos = new javax.swing.JButton();
        //list_infractions = new DefaultListModel<String>();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Infractions");

        //jL_list_infractions.setModel(list_infractions);
        jScrollPane2.setViewportView(jL_list_infractions);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Infractions");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Ajouter l'infraction au dossier");

        jLabel7.setText("Infraction");

        selectedInfraction.setText("SelectedInfraction");

        jLabel4.setText("Niveau de gravite");

        jL_niveauGravite.setText("0");

        jB_add_infToDos.setText("Ajouter au dossier");
        jB_add_infToDos.addActionListener(_listener);
        jB_add_infToDos.setActionCommand(String.valueOf(ClientVoitureSingleton.ADD_INFRACTION_TO_DOS));
        
        jL_list_infractions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	currentInfraction = jL_list_infractions.getSelectedItem();
            	selectedInfraction.setText(currentInfraction);
            	
            	// Search the string to retrieve the gravite
    			String[] selectedInfractionArr = currentInfraction.split(",");
    			Scanner in = new Scanner(selectedInfractionArr[2]).useDelimiter("[^0-9]+");
    			int selectedInfractionGravite = in.nextInt();
    			jL_niveauGravite.setText(Integer.toString(selectedInfractionGravite));
            }
        });
        

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jL_list_infractions, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selectedInfraction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jL_niveauGravite)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(86, 86, 86)
                                        .addComponent(jB_add_infToDos)))
                                .addGap(215, 215, 215)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(selectedInfraction))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jL_niveauGravite))
                        .addGap(18, 18, 18)
                        .addComponent(jB_add_infToDos))
                    .addComponent(jL_list_infractions, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    
    
    
    public String getCurrentInfraction()
    {
 	   return currentInfraction;
    }

    
    public void showCustomMessage(String message)
    {
 	   JOptionPane.showMessageDialog(null, message);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Infractions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Infractions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Infractions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Infractions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Infractions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private String currentInfraction;
    private javax.swing.JButton jB_add_infToDos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jL_niveauGravite;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel selectedInfraction;
    private java.awt.List jL_list_infractions;
    private javax.swing.JScrollPane jScrollPane2;
    //private DefaultListModel<String> list_infractions;
    // End of variables declaration
    
    public void refresh(CollectionInfraction collec_inf){
    	int size_infraction = collec_inf.size();
		//System.out.println("size_infraction="+size_infraction);
		if(size_infraction>0){
			int i=0;
			jL_list_infractions.removeAll();
			//System.out.println("[");
			while(size_infraction>i){ // Ajout des infractions a la liste des infractions
				//System.out.println("\tinf num="+i+": {"+banque_infraction.infractions().getInfraction(i)._toString()+"}");	
				jL_list_infractions.add(collec_inf.getInfraction(i)._toString()); // TODO makethis morep retty
				i++;
			}
			//System.out.println("]");
		}
    }
}
