/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.etsmtl.log720.lab1.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Scanner;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

import ca.etsmtl.log720.lab1.ClientVoitureSingleton;
import ca.etsmtl.log720.lab1.CollectionInfraction;
import ca.etsmtl.log720.lab1.CollectionReaction;

/**
 *
 * @author Steven
 */
public class Reactions extends javax.swing.JFrame {

    /**
     * Creates new form Reactions
     */
	private Reactions() {
        initComponents(new ActionListener(){
			public void actionPerformed(ActionEvent arg0) {
				// TODO Auto-generated method stub
				
			}
        });
    }
	
    public Reactions(ActionListener _listener) {
        initComponents(_listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents(ActionListener _listener) {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jL_list_reactions = new java.awt.List();
        jLabel2 = new javax.swing.JLabel();
        jT_description = new javax.swing.JTextField();
        jB_addList_Reaction = new javax.swing.JButton();
        jB_addList_Dossier = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jL_niveauGravite = new javax.swing.JLabel();
        jL_selectedReaction = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jT_gravite = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        //list_reaction = new DefaultListModel<String>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Réactions");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Reactions:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Ajouter une reaction:");

        jB_addList_Reaction.setText("Ajouter a la liste");
        jB_addList_Reaction.addActionListener(_listener);
        jB_addList_Reaction.setActionCommand(String.valueOf(ClientVoitureSingleton.ADD_REACTION_LIST));


        jB_addList_Dossier.setText("Ajouter au dossier");
        jB_addList_Dossier.addActionListener(_listener);
        jB_addList_Dossier.setActionCommand(String.valueOf(ClientVoitureSingleton.ADD_REACTION_TO_DOS));


        jLabel4.setText("Niveau de gravite");

        jL_niveauGravite.setText("0");

        jL_selectedReaction.setText("SelectedReaction");

        jLabel7.setText("Reaction");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Ajouter la reaction au dossier");

        jLabel3.setText("Description");

        jLabel9.setText("Gravite (1-5)");
        
        
        
        
        
        jL_list_reactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	currentReaction = jL_list_reactions.getSelectedItem();
            	jL_selectedReaction.setText(currentReaction);
            	
            	// Search the string to retrieve the gravite
    			String[] selectedReactionArr = currentReaction.split(",");
    			Scanner in = new Scanner(selectedReactionArr[2]).useDelimiter("[^0-9]+");
    			int selectedReactionGravite = in.nextInt();
    			jL_niveauGravite.setText(Integer.toString(selectedReactionGravite));
            }
        });
        

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_list_reactions, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jB_addList_Reaction)
                            .addComponent(jT_gravite, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(232, 232, 232))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(383, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addGap(223, 223, 223)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(117, 117, 117)
                            .addComponent(jB_addList_Dossier)
                            .addGap(233, 233, 233))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel4))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jL_selectedReaction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jL_niveauGravite)
                                            .addGap(0, 0, Short.MAX_VALUE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(295, 295, 295))
                                    .addComponent(jT_description, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(75, 75, 75))))
                            .addContainerGap()))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_list_reactions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jT_gravite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addComponent(jB_addList_Reaction)
                        .addGap(0, 250, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addGap(18, 18, 18)
                    .addComponent(jT_description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(136, 136, 136)
                    .addComponent(jLabel6)
                    .addGap(20, 20, 20)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jL_selectedReaction))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jL_niveauGravite))
                    .addGap(18, 18, 18)
                    .addComponent(jB_addList_Dossier)
                    .addContainerGap(79, Short.MAX_VALUE)))
        );

        getAccessibleContext().setAccessibleName("Reactions");

        pack();
    }// </editor-fold>             
    
    
    
    public String getDescription(){
  	   return jT_description.getText();
     }
     
     public int getGravite(){
     	//no need to try catch, this jint is overriden to only allow number
   	   return Integer.parseInt(jT_gravite.getText());
      }
     
     public void showCustomMessage(String message)
     {
     	JOptionPane.showMessageDialog(this, message);
     }
    
     public String getCurrentReaction()
     {
  	   return currentReaction;
     }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reactions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify    
    private String currentReaction;
    private javax.swing.JButton jB_addList_Reaction;
    private javax.swing.JButton jB_addList_Dossier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jL_niveauGravite;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jL_selectedReaction;
    private javax.swing.JLabel jLabel9;
    private java.awt.List jL_list_reactions;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jT_description;
    private javax.swing.JTextField jT_gravite;
    //private DefaultListModel<String> list_reaction;
    // End of variables declaration
    
    public void refresh(CollectionReaction collec_reac){
    	int size_reac = collec_reac.size();
		//System.out.println("size_infraction="+size_reac);
		if(size_reac>0){
			int i=0;
			jL_list_reactions.removeAll();
			//System.out.println("[");
			while(size_reac>i){ // Ajout des infractions a la liste des infractions
				//System.out.println("\tinf num="+i+": {"+banque_infraction.infractions().getInfraction(i)._toString()+"}");	
				jL_list_reactions.add(collec_reac.getReaction(i)._toString()); // TODO makethis morep retty
				i++;
			}
			//System.out.println("]");
		}
    }
}
