package ca.etsmtl.log720.lab1.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.DefaultListModel;

import ca.etsmtl.log720.lab1.ClientVoitureSingleton;
import ca.etsmtl.log720.lab1.CollectionDossier;
import ca.etsmtl.log720.lab1.CollectionInfraction;

/**
*
* @author Steven
*/
public class Recherche extends javax.swing.JFrame {

   /**
    * Creates new form Recherche
    */
   private Recherche() {
       initComponents(new ActionListener(){
			public void actionPerformed(ActionEvent arg0) {
				// TODO Auto-generated method stub
				
			}
       });
   }
	
   public Recherche(ActionListener _listener) {
       initComponents(_listener);
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents(ActionListener _listener) {
       jLabel1 = new javax.swing.JLabel();
       jScrollPane1 = new javax.swing.JScrollPane();
       list_dossier = new java.awt.List();
       jLabel6 = new javax.swing.JLabel();
       jLabel2 = new javax.swing.JLabel();
       jTF_nom = new javax.swing.JTextField();
       jLabel3 = new javax.swing.JLabel();
       jTF_prenom = new javax.swing.JTextField();
       jLabel4 = new javax.swing.JLabel();
       jTF_plaque = new javax.swing.JTextField();
       jLabel5 = new javax.swing.JLabel();
       jTF_permis = new javax.swing.JTextField();
       jB_searchDos = new javax.swing.JButton();
       jB_selectDos = new javax.swing.JButton();
       //list_dossier = new DefaultListModel<String>();

       setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
       setTitle("Recherche");

       jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
       jLabel1.setText("Recherche: ");

       jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
       jLabel6.setText("Resultats de la recherche");

       jLabel2.setText("Nom :");

       jLabel3.setText("Prenom :");

       jLabel4.setText("Numero de plaque :");

       jLabel5.setText("Numero de permis :");

       jB_searchDos.setText("Rechercher");
       jB_searchDos.addActionListener(_listener);
       jB_searchDos.setActionCommand(String.valueOf(ClientVoitureSingleton.SEARCH_DOS));

       jB_selectDos.setText("Selectionner le dossier");
       jB_selectDos.addActionListener(_listener);
       jB_selectDos.setActionCommand(String.valueOf(ClientVoitureSingleton.SELECT_DOS));

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                   .addGroup(layout.createSequentialGroup()
                       .addComponent(jLabel4)
                       .addGap(18, 18, 18)
                       .addComponent(jTF_plaque))
                   .addComponent(jLabel1)
                   .addGroup(layout.createSequentialGroup()
                       .addGap(51, 51, 51)
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                           .addComponent(jLabel3)
                           .addComponent(jLabel2))
                       .addGap(18, 18, 18)
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addComponent(jTF_prenom, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                           .addComponent(jTF_nom)))
                   .addGroup(layout.createSequentialGroup()
                       .addComponent(jLabel5)
                       .addGap(18, 18, 18)
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(jB_searchDos)
                           .addComponent(jTF_permis, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jB_selectDos)
                   .addComponent(jLabel6)
                   .addComponent(list_dossier, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGap(25, 25, 25))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jLabel1)
                   .addComponent(jLabel6))
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(layout.createSequentialGroup()
                       .addGap(38, 38, 38)
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(jLabel2)
                           .addComponent(jTF_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                       .addGap(18, 18, 18)
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(jLabel3)
                           .addComponent(jTF_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                       .addGap(18, 18, 18)
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(jLabel4)
                           .addComponent(jTF_plaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(jLabel5)
                           .addComponent(jTF_permis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                       .addGap(34, 34, 34)
                       .addComponent(jB_searchDos))
                   .addGroup(layout.createSequentialGroup()
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addComponent(list_dossier, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
               .addGap(19, 19, 19)
               .addComponent(jB_selectDos)
               .addContainerGap(43, Short.MAX_VALUE))
       );

       pack();
   }// </editor-fold>          
   
   
   
   public String getPrenom()
   {
	   String prenom = jTF_nom.getText();
	   return prenom;
   }
   public String getNom()
   {
	   String nom = jTF_prenom.getText();
	   return nom;
   }
   public String getPlaque()
   {
	   String plaque = jTF_plaque.getText();
	   return plaque;
   }
   public String getPermis()
   {
	   String permis = jTF_permis.getText();
	   return permis;
   }
   
   public String getSelectedDossier()
   {
	   return list_dossier.getSelectedItem();
   }
   
   
   

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
       /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
       /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        */
       try {
           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               if ("Nimbus".equals(info.getName())) {
                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   break;
               }
           }
       } catch (ClassNotFoundException ex) {
           java.util.logging.Logger.getLogger(Recherche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (InstantiationException ex) {
           java.util.logging.Logger.getLogger(Recherche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           java.util.logging.Logger.getLogger(Recherche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           java.util.logging.Logger.getLogger(Recherche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       }
       //</editor-fold>

       /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               new Recherche().setVisible(true);
           }
       });
   }

   // Variables declaration - do not modify                     
   private javax.swing.JButton jB_searchDos;
   private javax.swing.JButton jB_selectDos;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private java.awt.List list_dossier;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTextField jTF_nom;
   private javax.swing.JTextField jTF_prenom;
   private javax.swing.JTextField jTF_plaque;
   private javax.swing.JTextField jTF_permis;
   //private DefaultListModel<String> list_dossier;
   // End of variables declaration 
   
   public void refresh(CollectionDossier collec_dos){
		int size_dos = collec_dos.size();
		//System.out.println("size_infraction="+size_infraction);
		if(size_dos>0){
			int i=0;
			list_dossier.removeAll();
			//System.out.println("[");
			while(size_dos>i){
				//	System.out.println("\tdos num="+i+": {"+collec_doc.getDossier(i)._toString()+"}");
					// Ajout des dossiers a la liste des dossiers
					
					list_dossier.add(collec_dos.getDossier(i)._toString());
					i++;
				}
				//System.out.println("]");
			}
			repaint();
	}
}