/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.etsmtl.log720.lab1.view;

import java.awt.event.ActionListener;

import ca.etsmtl.log720.lab1.ClientPosteSingleton;
import ca.etsmtl.log720.lab1.CollectionDossier;

/**
*
* @author Steven
*/
public class Dossiers extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ActionListener listener;
   /**
    * Creates new form Dossiers
    * @param listener 
    */
   public Dossiers(ActionListener listener) {
       initComponents();
       this.listener = listener;
   }
   
   private Dossiers() {
       initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents() {

       jFrame1 = new javax.swing.JFrame();
       jLabel1 = new javax.swing.JLabel();
       jScrollPane1 = new javax.swing.JScrollPane();
       jList1 = new javax.swing.JList();
       jLabel6 = new javax.swing.JLabel();
       jLabel2 = new javax.swing.JLabel();
       jTextField1 = new javax.swing.JTextField();
       jLabel3 = new javax.swing.JLabel();
       jTextField2 = new javax.swing.JTextField();
       jLabel4 = new javax.swing.JLabel();
       jTextField3 = new javax.swing.JTextField();
       jLabel5 = new javax.swing.JLabel();
       jTextField4 = new javax.swing.JTextField();
       jButton1 = new javax.swing.JButton();
       jButton4 = new javax.swing.JButton();
       jLabel9 = new javax.swing.JLabel();
       jLabel10 = new javax.swing.JLabel();
       jButton3 = new javax.swing.JButton();
       jLabel7 = new javax.swing.JLabel();
       jTextField5 = new javax.swing.JTextField();
       jLabel8 = new javax.swing.JLabel();
       jLabel12 = new javax.swing.JLabel();
       jLabel13 = new javax.swing.JLabel();
       jTextField6 = new javax.swing.JTextField();
       jTextField7 = new javax.swing.JTextField();
       jTextField8 = new javax.swing.JTextField();
       list1 = new java.awt.List();

       jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
       jFrame1.setTitle("Recherche");

       jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
       jLabel1.setText("Recherche: ");

       jList1.setModel(new javax.swing.AbstractListModel() {
           /**
		 * 
		 */
		private static final long serialVersionUID = 1L;
		String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
           public int getSize() { return strings.length; }
           public Object getElementAt(int i) { return strings[i]; }
       });
       jScrollPane1.setViewportView(jList1);

       jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
       jLabel6.setText("Résultats de la recherche");

       jLabel2.setText("Nom :");

       jLabel3.setText("Prénom :");

       jLabel4.setText("Numéro de plaque :");

       jLabel5.setText("Numéro de permis :");

       jButton1.setText("Rechercher");

       jButton4.setText("Sélectionner le dossier");
       jButton4.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton4ActionPerformed(evt);
           }
       });

       javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
       jFrame1.getContentPane().setLayout(jFrame1Layout);
       jFrame1Layout.setHorizontalGroup(
           jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                   .addGroup(jFrame1Layout.createSequentialGroup()
                       .addComponent(jLabel4)
                       .addGap(18, 18, 18)
                       .addComponent(jTextField3))
                   .addComponent(jLabel1)
                   .addGroup(jFrame1Layout.createSequentialGroup()
                       .addGap(51, 51, 51)
                       .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                           .addComponent(jLabel3)
                           .addComponent(jLabel2))
                       .addGap(18, 18, 18)
                       .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                           .addComponent(jTextField1)))
                   .addGroup(jFrame1Layout.createSequentialGroup()
                       .addComponent(jLabel5)
                       .addGap(18, 18, 18)
                       .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(jButton1)
                           .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
               .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jButton4)
                   .addComponent(jLabel6)
                   .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addContainerGap())
       );
       jFrame1Layout.setVerticalGroup(
           jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jFrame1Layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jLabel1)
                   .addComponent(jLabel6))
               .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(jFrame1Layout.createSequentialGroup()
                       .addGap(38, 38, 38)
                       .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(jLabel2)
                           .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                       .addGap(18, 18, 18)
                       .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(jLabel3)
                           .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                       .addGap(18, 18, 18)
                       .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(jLabel4)
                           .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                       .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(jLabel5)
                           .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                       .addGap(34, 34, 34)
                       .addComponent(jButton1))
                   .addGroup(jFrame1Layout.createSequentialGroup()
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
               .addGap(18, 18, 18)
               .addComponent(jButton4)
               .addContainerGap(43, Short.MAX_VALUE))
       );

       setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
       setTitle("Dossiers (poste)");

       jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
       jLabel9.setText("Dossiers :");

       jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
       jLabel10.setText("Ajouter un dossier:");

       jButton3.setText("Ajouter un dossier");
       jButton3.addActionListener(listener);
       jButton3.setActionCommand(String.valueOf(ClientPosteSingleton.ADD_DOSSIER));

       jLabel7.setText("Nom :");

       jLabel8.setText("Prenom :");

       jLabel12.setText("Numero de plaque :");

       jLabel13.setText("Numero de permis :");

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(layout.createSequentialGroup()
                       .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addContainerGap())
                   .addGroup(layout.createSequentialGroup()
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(jLabel9)
                           .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                               .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                   .addGap(351, 351, 351)
                                   .addComponent(jButton3))
                               .addGroup(layout.createSequentialGroup()
                                   .addGap(0, 337, Short.MAX_VALUE)
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                       .addGroup(layout.createSequentialGroup()
                                           .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                               .addComponent(jLabel8)
                                               .addComponent(jLabel12)
                                               .addComponent(jLabel13))
                                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                           .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                               .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                               .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                               .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                       .addGroup(layout.createSequentialGroup()
                                           .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                               .addComponent(jLabel7)
                                               .addComponent(jLabel10))
                                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                           .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                       .addContainerGap(38, Short.MAX_VALUE))))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(jLabel9)
               .addGap(18, 18, 18)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(layout.createSequentialGroup()
                       .addComponent(jLabel10)
                       .addGap(25, 25, 25)
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(jLabel7)
                           .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(jLabel8)
                           .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(jLabel12)
                           .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(jLabel13)
                           .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                       .addGap(32, 32, 32)
                       .addComponent(jButton3)
                       .addGap(0, 123, Short.MAX_VALUE))
                   .addComponent(list1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addContainerGap())
       );

       pack();
   }// </editor-fold>                        
                                 

   private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       // setSelectedDossier(selectedItem);
       dispose();
   }                                        

   public String getPrenom()
   {
	   String prenom = jTextField5.getText();
	   return prenom;
   }
   public String getNom()
   {
	   String nom = jTextField6.getText();
	   return nom;
   }
   public String getPlaque()
   {
	   String plaque = jTextField7.getText();
	   return plaque;
   }
   public String getPermis()
   {
	   String permis = jTextField8.getText();
	   return permis;
   }
   
   
   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
       /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
       /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        */
       try {
           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               if ("Nimbus".equals(info.getName())) {
                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   break;
               }
           }
       } catch (ClassNotFoundException ex) {
           java.util.logging.Logger.getLogger(Dossiers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (InstantiationException ex) {
           java.util.logging.Logger.getLogger(Dossiers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           java.util.logging.Logger.getLogger(Dossiers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           java.util.logging.Logger.getLogger(Dossiers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       }
       //</editor-fold>

       /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               new Dossiers().setVisible(true);
           }
       });
   }

   // Variables declaration - do not modify                     
   private javax.swing.JButton jButton1;
   public javax.swing.JButton jButton3;
   private javax.swing.JButton jButton4;
   private javax.swing.JFrame jFrame1;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel10;
   private javax.swing.JLabel jLabel12;
   private javax.swing.JLabel jLabel13;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel7;
   private javax.swing.JLabel jLabel8;
   private javax.swing.JLabel jLabel9;
   private javax.swing.JList jList1;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTextField jTextField1;
   private javax.swing.JTextField jTextField2;
   private javax.swing.JTextField jTextField3;
   private javax.swing.JTextField jTextField4;
   private javax.swing.JTextField jTextField5;
   private javax.swing.JTextField jTextField6;
   private javax.swing.JTextField jTextField7;
   private javax.swing.JTextField jTextField8;
   public java.awt.List list1;
   // End of variables declaration    
   
	public void refresh(CollectionDossier collec_doc){
		int size_dossiers = collec_doc.size();
		//System.out.println("size_dossiers="+size_dossiers);
		if(size_dossiers>0){
			int i=0;
			list1.removeAll();
			//System.out.println("[");
			while(size_dossiers>i){
			//	System.out.println("\tdos num="+i+": {"+collec_doc.getDossier(i)._toString()+"}");
				// Ajout des dossiers a la liste des dossiers
				
				list1.add(collec_doc.getDossier(i)._toString());
				i++;
			}
			//System.out.println("]");
		}
		repaint();
	}
}
