// Generated Nov 10, 2014 2:00:27 PM by Hibernate Tools 3.4.0.CR1
package springapp.domain;

import java.util.HashSet;
import java.util.Set;

/**
 * Infraction generated by hbm2java
 */
public class Infraction implements java.io.Serializable {

	private int id;
	private String description;
	private Integer niveau;
	private Set dosinfractions = new HashSet(0);

	public Infraction() {
	}

	public Infraction(int id, String description) {
		this.id = id;
		this.description = description;
	}

	public Infraction(int id, String description, Integer niveau,
			Set dosinfractions) {
		this.id = id;
		this.description = description;
		this.niveau = niveau;
		this.dosinfractions = dosinfractions;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getNiveau() {
		return this.niveau;
	}

	public void setNiveau(Integer niveau) {
		this.niveau = niveau;
	}

	public Set getDosinfractions() {
		return this.dosinfractions;
	}

	public void setDosinfractions(Set dosinfractions) {
		this.dosinfractions = dosinfractions;
	}

}
