// Generated Nov 10, 2014 2:00:27 PM by Hibernate Tools 3.4.0.CR1
package ca.etsmtl.log720.lab3.domain;

import java.util.Date;

/**
 * DosinfractionId generated by hbm2java
 */
public class DosinfractionId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int iddossier;
	private int idinfraction;
	private Date date;

	public DosinfractionId() {
	}

	public DosinfractionId(int iddossier, int idinfraction, Date date) {
		this.iddossier = iddossier;
		this.idinfraction = idinfraction;
		this.date = date;
	}

	public int getIddossier() {
		return this.iddossier;
	}

	public void setIddossier(int iddossier) {
		this.iddossier = iddossier;
	}

	public int getIdinfraction() {
		return this.idinfraction;
	}

	public void setIdinfraction(int idinfraction) {
		this.idinfraction = idinfraction;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DosinfractionId))
			return false;
		DosinfractionId castOther = (DosinfractionId) other;

		return (this.getIddossier() == castOther.getIddossier())
				&& (this.getIdinfraction() == castOther.getIdinfraction())
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null
						&& castOther.getDate() != null && this.getDate()
						.equals(castOther.getDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIddossier();
		result = 37 * result + this.getIdinfraction();
		result = 37 * result
				+ (getDate() == null ? 0 : this.getDate().hashCode());
		return result;
	}

}
