// Generated Nov 10, 2014 2:00:27 PM by Hibernate Tools 3.4.0.CR1
package ca.etsmtl.log720.lab3.domain;

/**
 * Dosinfraction generated by hbm2java
 */
public class Dosinfraction implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private DosinfractionId id;
	private Dossier dossier;
	private Infraction infraction;

	public Dosinfraction() {
	}

	public Dosinfraction(DosinfractionId id, Dossier dossier,
			Infraction infraction) {
		this.id = id;
		this.dossier = dossier;
		this.infraction = infraction;
	}

	public DosinfractionId getId() {
		return this.id;
	}

	public void setId(DosinfractionId id) {
		this.id = id;
	}

	public Dossier getDossier() {
		return this.dossier;
	}

	public void setDossier(Dossier dossier) {
		this.dossier = dossier;
	}

	public Infraction getInfraction() {
		return this.infraction;
	}

	public void setInfraction(Infraction infraction) {
		this.infraction = infraction;
	}

}
