// Generated Nov 10, 2014 2:00:27 PM by Hibernate Tools 3.4.0.CR1
package ca.etsmtl.log720.lab3.domain;

import java.util.HashSet;
import java.util.Set;

/**
 * Dossier generated by hbm2java
 */
public class Dossier implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String nom;
	private String prenom;
	private String nopermis;
	private String noplaque;
	private Integer niveau;
	private Set<Dosinfraction> dosinfractions = new HashSet<Dosinfraction>(0);

	public Dossier() {
	}

	public Dossier(int id, String nopermis, String noplaque) {
		this.id = id;
		this.nopermis = nopermis;
		this.noplaque = noplaque;
	}

	public Dossier(int id, String nom, String prenom, String nopermis,
			String noplaque, Integer niveau, Set<Dosinfraction> dosinfractions) {
		this.id = id;
		this.nom = nom;
		this.prenom = prenom;
		this.nopermis = nopermis;
		this.noplaque = noplaque;
		this.niveau = niveau;
		this.dosinfractions = dosinfractions;
		calcNiveau();
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getNopermis() {
		return this.nopermis;
	}

	public void setNopermis(String nopermis) {
		this.nopermis = nopermis;
	}

	public String getNoplaque() {
		return this.noplaque;
	}

	public void setNoplaque(String noplaque) {
		this.noplaque = noplaque;
	}

	public Integer getNiveau() {
		return this.niveau;
	}

	public void setNiveau(Integer niveau) {
		this.niveau = niveau;
	}

	public Set<Dosinfraction> getDosinfractions() {
		return this.dosinfractions;
	}

	public void setDosinfractions(Set<Dosinfraction> dosinfractions) {
		this.dosinfractions = dosinfractions;
		calcNiveau();
	}
	
	public int calcNiveau(){
		int niveau=0;
		for( Dosinfraction cur : this.dosinfractions){
			int tmp = cur.getInfraction().getNiveau();
			if(tmp > niveau)
				niveau = tmp;
		}
		setNiveau(niveau);
		return niveau;
	}

}
